/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: 'class',
  content: [
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        "outline-variant": "#424754",
        "on-primary-fixed-variant": "#004395",
        "background": "#0b1326",
        "on-tertiary-fixed": "#311400",
        "tertiary": "#ffb786",
        "surface-variant": "#2d3449",
        "glass-surface": "rgba(255, 255, 255, 0.05)",
        "primary-fixed": "#d8e2ff",
        "error-container": "#93000a",
        "surface": "#0b1326",
        "surface-dim": "#0b1326",
        "primary": "#adc6ff",
        "inverse-on-surface": "#283044",
        "tertiary-fixed-dim": "#ffb786",
        "warning": "#F59E0B",
        "secondary-container": "#571bc1",
        "on-secondary-fixed": "#23005c",
        "on-error-container": "#ffdad6",
        "on-background": "#dae2fd",
        "on-error": "#690005",
        "inverse-surface": "#dae2fd",
        "surface-container-low": "#131b2e",
        "surface-bright": "#31394d",
        "glass-border": "rgba(255, 255, 255, 0.1)",
        "error": "#EF4444",
        "on-primary-container": "#00285d",
        "surface-container-highest": "#2d3449",
        "surface-tint": "#adc6ff",
        "outline": "#8c909f",
        "on-secondary-container": "#c4abff",
        "success": "#22C55E",
        "on-secondary": "#3c0091",
        "surface-container": "#171f33",
        "primary-container": "#4d8eff",
        "on-surface-variant": "#c2c6d6",
        "secondary-fixed": "#e9ddff",
        "inverse-primary": "#005ac2",
        "on-surface": "#dae2fd",
        "surface-container-lowest": "#060e20",
        "secondary": "#d0bcff",
        "on-primary": "#002e6a",
        "primary-fixed-dim": "#adc6ff",
        "tertiary-fixed": "#ffdcc6",
        "on-primary-fixed": "#001a42",
        "on-secondary-fixed-variant": "#5516be",
        "on-tertiary-container": "#461f00",
        "on-tertiary-fixed-variant": "#723600",
        "surface-container-high": "#222a3d",
        "on-tertiary": "#502400",
        "secondary-fixed-dim": "#d0bcff",
        "muted": "#64748B",
        "tertiary-container": "#df7412"
      },
      borderRadius: {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "full": "9999px"
      },
      spacing: {
        "gutter": "16px",
        "base": "4px",
        "xs": "4px",
        "lg": "24px",
        "xl": "48px",
        "margin-desktop": "32px",
        "md": "16px",
        "margin-mobile": "16px",
        "sm": "8px"
      }
    },
  },
  plugins: [],
}
